"""
Django settings for hello project.
Generated by 'django-admin startproject' using Django 5.2.
"""

import os
import sys
from pathlib import Path
from distutils.util import strtobool

# -------------------------------
# Base directory
# -------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -------------------------------
# Security
# -------------------------------
SECRET_KEY = os.environ.get("SECRET_KEY", "dev-secret-key-change-me")

DEBUG = bool(strtobool(os.getenv("DEBUG", "false")))

TESTING = "test" in sys.argv

# Allowed Hosts
allowed_hosts = os.getenv("ALLOWED_HOSTS", ".localhost,127.0.0.1,[::1]")
ALLOWED_HOSTS = [h.strip() for h in allowed_hosts.split(",")]

# -------------------------------
# Applications
# -------------------------------
INSTALLED_APPS = [
    "pages.apps.PagesConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

# Add Debug Toolbar only when not testing
if not TESTING:
    INSTALLED_APPS += ["debug_toolbar"]

# -------------------------------
# Middleware
# -------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if not TESTING:
    MIDDLEWARE = ["debug_toolbar.middleware.DebugToolbarMiddleware"] + MIDDLEWARE

# -------------------------------
# URL & WSGI
# -------------------------------
ROOT_URLCONF = "config.urls"
WSGI_APPLICATION = "config.wsgi.application"

# -------------------------------
# Templates
# -------------------------------
default_loaders = [
    "django.template.loaders.filesystem.Loader",
    "django.template.loaders.app_directories.Loader",
]

cached_loaders = [("django.template.loaders.cached.Loader", default_loaders)]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "loaders": default_loaders if DEBUG else cached_loaders,
        },
    },
]

# -------------------------------
# Database (PostgreSQL for Docker)
# -------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "hello"),
        "USER": os.getenv("POSTGRES_USER", "hello"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "password"),
        "HOST": os.getenv("POSTGRES_HOST", "db"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}

# -------------------------------
# Password Validation
# -------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -------------------------------
# Defaults
# -------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Sessions stored in cookies
SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"

# -------------------------------
# Redis
# -------------------------------
# Prefer explicit host/port environment variables so code works both inside
# Docker networks (where host=redis) and CI runners or local dev (where
# host=localhost). Defaults use localhost which is appropriate for GitHub
# Actions service containers.
REDIS_HOST = os.getenv("REDIS_HOST", "localhost")
REDIS_PORT = int(os.getenv("REDIS_PORT", "6379"))
REDIS_URL = os.getenv("REDIS_URL", f"redis://{REDIS_HOST}:{REDIS_PORT}/0")

# -------------------------------
# STATIC FILES (FIXED)
# -------------------------------
# Required for Django staticfiles app
STATIC_URL = "/static/"

# This is where files get collected during `collectstatic`
STATIC_ROOT = BASE_DIR / "staticfiles"

# Extra static folders (safe - only if folder exists)
STATICFILES_DIRS = [
    BASE_DIR / "public",
    # Also include the project's `assets/static` folder so built or example
    # static files bundled in the `assets` directory are collected.
    BASE_DIR.parent / "assets" / "static",
]

# Whitenoise compressed cached storage
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
